spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:content
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true