{
    "account_status": "ACTIVE",
    "cost_centre": "",
    "dns_name": "",
    "dns_server": "",
    "domain": "",
    "end_of_operation": "",
    "id": 57,
    "inventory_item": "",
    "inventory_number": "",
    "ip_address": "",
    "ip_v6_address": "",
    "location": "",
    "manufacturer": "",
    "model": "",
    "name": "",
    "operation_system": "WINDOWS11",
    "operational_impact": "PERSON",
    "operational_status": "UNKNOWN",
    "organizational_unit": "",
    "owner": {
        "district": "Bemposta",
        "first_name": "Munroe",
        "home": "97028",
        "id": 57,
        "last_name": "Ardley",
        "number": "125-288-3251",
        "postal_code": "4730-010",
        "street": "7109 Pankratz Plaza"
        },
    "processor": "",
    "property": "UNKNOWN",
    "serial_number": "",
    "standard_gateway": "",
    "status": "UNKNOWN",
    "year_of_manufacture": ""
}